### ISSUE TITLE
Potential small bug

### ISSUE THREAD

**Issue by innopage** [ruipgil/scraperjs#26]
In ScraperPromise.js line 282.  Do you mean to call this.doneCallBack() with (utils) ?

because I'm getting a crash onError with a stack trace like this:

TypeError: Cannot read property 'lastReturn' of undefined
    at doneCallback (/home/innopage/node_modules/scraperjs/src/ScraperPromise.js:28:15)
    at ScraperPromise._fire (/home/innopage/node_modules/scraperjs/src/ScraperPromise.js:282:9)
    at /home/innopage/node_modules/scraperjs/src/ScraperPromise.js:230:9
    at Request.processGet [as _callback] (/home/innopage/node_modules/scraperjs/src/AbstractScraper.js:59:5)
    at self.callback (/home/innopage/node_modules/scraperjs/node_modules/request/request.js:123:22)
    at Request.emit (events.js:95:17)
    at ClientRequest.self.clientErrorHandler (/home/innopage/node_modules/scraperjs/node_modules/request/request.js:244:10)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketOnEnd [as onend] (http.js:1573:9)
    at Socket.g (events.js:180:16)

**Comment by ruipgil** [comment]
Thanks, it's a bug definitely.
Would you make a pull request, since you found the bug, or should I correct it?
